# Permalinks
permalink:           pretty

# Setup
title:               Augusto Guerrero
tagline:             Argentinian developer
url:                 http://augustoguerrero.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Augusto Guerrero
  url:               https://twitter.com/fffffffffuu
  email:             augusto.codex@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/augustoguerrero

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
